[package]
name = "ractor-316"
version = "0.1.0"
edition = "2021"

[dependencies]
ractor = "0.14.3"
tokio = { version = "1.42.0", features = ["process", "rt-multi-thread", "tokio-macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
